version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2:1521//opt/h2-data/test
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - h2

  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "9092:9092"
      - "81:81"
    volumes:
      - ./h2data:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists